<?php
// download_failed_records.php
// Streams the failed-records CSV generated by upload_members.php.
// Only allows downloading the file that this session's upload just created,
// and only from the expected directory, to prevent path traversal / arbitrary
// file disclosure.

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$downloadDir = realpath("../resources/uploads/failed_imports/");
$requestedFile = isset($_GET['file']) ? basename($_GET['file']) : '';

if (
    empty($requestedFile) ||
    !isset($_SESSION['failed_import_file']) ||
    $_SESSION['failed_import_file'] !== $requestedFile
) {
    http_response_code(403);
    echo "Error: File not found or you do not have permission to download it.";
    exit;
}

$filePath = $downloadDir . DIRECTORY_SEPARATOR . $requestedFile;

if (!$downloadDir || !file_exists($filePath) || dirname(realpath($filePath)) !== $downloadDir) {
    http_response_code(404);
    echo "Error: File not found.";
    exit;
}

header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="' . $requestedFile . '"');
header('Content-Length: ' . filesize($filePath));
header('Pragma: no-cache');
header('Expires: 0');

readfile($filePath);

// Optional: clean up the temp file after download so it doesn't linger
// unlink($filePath);
// unset($_SESSION['failed_import_file']);

exit;